languageCode = "en-us"
title = "Kodacell - Immersive Web"
canonifyurls = true

[params]
    author = "Shaun Davis"
    description = "Immersive Web"
    githubUsername = "shaun1x"
    accent = "#1fcbff"
    showBorder = false
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

 [[menu.main]]
     url = "/post/"
     name = "/Blog"
     weight = 2

 [[menu.main]]
    url = "/work/"
    name = "/work"
    weight = 3

# [[menu.main]]
#     url = "/lab/"
#     name = "The Lab"
#     weight = 4

[[menu.main]]
    url = "/quotes/"
    name = "/Quotes"
    weight = 4

[[menu.main]]
    url = "/live/"
    name = "/Live"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:shaun@kodacell.com"
    name = "icon-mail-alt"
    weight = 5

[[menu.icon]]
    url = "https://github.com/shaunmnemonic/"
    name = "icon-github-circled"
    weight = 3

[[menu.icon]]
    url = "https://twitter.com/shaunmnemonic/"
    name = "icon-twitter"
    weight = 4

[[menu.icon]]
    url = "https://www.linkedin.com/in/shaunix/"
    name = "icon-linkedin"
    weight = 6

[[menu.icon]]
    url = "https://www.twitch.tv/shaunixx"
    name = "icon-twitch"
    weight = 1

[[menu.icon]]
    url = "https://www.youtube.com/channel/UC_22XvsUjhYHHinHe_RLjqw"
    name = "icon-youtube-play"
    weight = 2
